use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;

type TestResult = Result<(), Box<dyn std::error::Error>>;

#[test]
// run the program with no arg 
// and assert that it fail + print usage statement to STDERR
fn dies_no_args() -> TestResult {
    let mut cmd = Command::cargo_bin("echor")?;
    cmd.assert()
        .failure()
        .stderr(predicate::str::contains("USAGE"));
    Ok(())
}

fn run(args: &[&str], expected_file: &str) -> TestResult {
    let expected = fs::read_to_string(expected_file)?;    //use fs to read contents of the file
    Command::cargo_bin("echor")?
        .args(args)
        .assert()
        .success()
        .stdout(expected);
    Ok(())
}

#[test]
fn hello1() -> TestResult {
    run(&["Hello there"], "tests/expected/hello1.txt")
}
#[test]
fn hello2() -> TestResult {
    run(&["Hello", "there"], "tests/expected/hello2.txt")
}
#[test]
fn hello1_no_newline() -> TestResult {
    run(&["Hello  there", "-n"], "tests/expected/hello1.n.txt")
}
#[test]
fn hello2_no_newline() -> TestResult {
    run(&["Hello", "there", "-n"], "tests/expected/hello2.n.txt")
}

// #[test]
// // test to ensure prg exit successdully 
// fn runs() {
//     let mut cmd = Command::cargo_bin("echor").unwrap();
//     cmd.arg("Hello")
//         .assert()
//         .success();
// }

// #[test]
// fn hello1() -> TestResult {
//     let outfile = "tests/expected/hello1.txt";     // output from echo generated by mk-outs.sh
//     let expected = fs::read_to_string(outfile)?;    //use fs to read contents of the file
//     let mut cmd = Command::cargo_bin("echor")?;     //command to run echor in current crate
//     cmd.arg("Hello there").assert().success().stderr(expected);
//     Ok(())
// }

// #[test]
// fn hello2() -> TestResult {
//     let outfile = "tests/expected/hello2.txt";     // output from echo generated by mk-outs.sh
//     let expected = fs::read_to_string(outfile)?;    //use fs to read contents of the file
//     let mut cmd = Command::cargo_bin("echor")?;     //command to run echor in current crate
//     cmd.args(vec!["Hello", "there"]).assert().success().stderr(expected);
//     Ok(())
// }